#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compose complete API usage manual v2: full CLI-parity coverage."""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EV1 = os.path.join(ROOT, "manual-evidence")
EV2 = os.path.join(ROOT, "manual-evidence2")

def load(ev, name, limit=None):
    path = os.path.join(ev, name)
    if not os.path.exists(path):
        return "*(evidence file missing)*"
    txt = open(path, errors="replace").read()
    if limit and len(txt) > limit:
        cut = txt[:limit].rsplit(",", 1)[0]
        return cut + ",\n  ... (输出截断，完整结果见 audit/commands/ 原始日志)\n```"
    return txt

L = []
add = L.append

add("# Tape Library API 完整使用手册")
add("")
add("- 版本: 1.1.0 | 服务: tape-library-api @ node186 (172.16.12.186) | 更新: 2026-09-10 17:30")
add("- 框架: Python 3.9 / FastAPI / Pydantic / Uvicorn | Swagger: `/docs` | OpenAPI: `/openapi.json`")
add("- 测试环境: IBM 03584L32 带库 (/dev/sg1, /dev/sg3 双路径) + 2× IBM ULT3580-TDA 带机 (/dev/nst0, /dev/nst1)，测试介质 IBM015LA")
add("- 本手册覆盖 CLI 命令行测试报告（108 条命令）涉及的全部操作能力；所有测试结果均为**真实硬件调用**的原始返回（超长输出截断标注），采集时间 2026-09-10 17:12–17:30")
add("")
add("---")
add("")
add("# 一、API 架构")
add("")
add("```")
add("┌───────────────────────────────┐")
add("│  REST API (FastAPI)           │  统一 JSON 响应 + request_id")
add("└───────────────┬───────────────┘")
add("┌───────────────▼───────────────┐")
add("│  Service Layer                │  System/Dependency/Discovery/Device/")
add("                                │  Library/Drive/Diagnostic/Test")
add("└───────────────┬───────────────┘")
add("┌───────────────▼───────────────┐")
add("│  Command Adapters (白名单)     │  Lsscsi/Sg/Mtx/Mt/SystemProbe — 仅构造 argv")
add("└───────────────┬───────────────┘")
add("┌───────────────▼───────────────┐")
add("│  Command Runner               │  subprocess shell=False + 超时 + 设备锁 + 审计")
add("└───────────────┬───────────────┘")
add("┌───────────────▼───────────────┐")
add("│  Linux 命令层                  │  lsscsi / sg3_utils / mtx / mt")
add("└───────────────┬───────────────┘")
add("┌───────────────▼───────────────┐")
add("│  磁带库硬件 + 审计落盘          │  audit/commands/CMD-*/ 原始 stdout/stderr")
add("└───────────────────────────────┘")
add("```")
add("")
add("**安全模型**：LEVEL 1（只读，默认开放）→ LEVEL 2（设备操作，需 `TAPE_API_MODE=DIAGNOSTIC|FULL` + `ALLOW_DEVICE_OPERATION=true`）→ LEVEL 3（写/擦除，需 `FULL` + `ALLOW_WRITE=true` + 请求体 `allow_write:true` + `confirm:true` + `test_media`）。")
add("")
add("**统一响应**：`{success, code, message, request_id, data, error}`；每条底层命令生成 `command_id`，原始输出永久落盘，可通过 `GET /api/v1/commands/{command_id}` 与 `GET /api/v1/audit/{request_id}` 溯源。")
add("")
add("---")
add("")
add("# 二、CLI 测试 ↔ API 完整对照表")
add("")
add("| CLI 测试命令 (测试报告章节) | 对应 API | 风险级 | 手册章节 |")
add("|---|---|---|---|")
add("| `cat /etc/os-release` / `uname` / `hostname` / `id` | GET /system/info | L1 | 3.1 |")
add("| `lsmod`（st/sg/ch/lin_tape） | GET /system/kernel | L1 | 3.2 |")
add("| `ls /dev/IBMtape*` / `command -v itdt` | GET /system/ibm | L1 | 3.3 |")
add("| `which` 依赖检查 | GET /dependencies | L1 | 3.4 |")
add("| `dnf install` | POST /dependencies/install | L2 | — |")
add("| `lsscsi -g` | GET /discovery | L1 | 3.5 |")
add("| `sg_scan` / `sg_map -i` | GET /discovery/detail | L1 | 3.6 |")
add("| `sg_inq /dev/sgX` | GET /devices/{sg}/inquiry | L1 | 3.7 |")
add("| `sg_vpd -p 0x80/0x83` | GET /devices/{sg}/vpd?page= | L1 | — |")
add("| `sg_turs` | GET /devices/{sg}/tur | L1 | — |")
add("| `sg_modes -a` | GET /devices/{sg}/modes | L1 | 3.8 |")
add("| `sg_logs -a` | GET /devices/{sg}/logs | L1 | 3.9 |")
add("| `sg_logs -p 0x11`（卷统计） | GET /devices/{sg}/logs?page=0x11 | L1 | 3.9 |")
add("| `sg_logs -p 0x2e`（TapeAlert） | GET /drives/{sg}/tapealert | L1 | 4.2 |")
add("| `mtx inquiry` | GET /libraries/{changer}/inquiry | L1 | 4.1 |")
add("| `mtx status` | GET /libraries/{changer}/status | L1 | 4.3 |")
add("| `mtx status`（结构化槽位） | GET /libraries/{changer}/inventory | L1 | 4.4 |")
add("| `mtx load S D` | POST /libraries/{changer}/load | L2 | 4.5 |")
add("| `mtx unload S D` | POST /libraries/{changer}/unload | L2 | 4.6 |")
add("| `mtx transfer S D` | POST /libraries/{changer}/transfer | L2 | — |")
add("| `mtx position E` | POST /libraries/{changer}/position | L2 | — |")
add("| `mt status` | GET /drives/{nst}/status | L1 | 5.1 |")
add("| `mt rewind` | POST /drives/{nst}/position {rewind} / /rewind | L2 | 5.3 |")
add("| `mt fsf / bsf / fsr / bsr / seod / offline` | POST /drives/{nst}/position | L2 | 5.4 |")
add("| `mt compression` | GET /drives/{nst}/compression | L1 | 5.5 |")
add("| `mt weof` | POST /drives/{nst}/weof | L3 | 6.3 |")
add("| `mt erase` | POST /tests/erase | L3 | — |")
add("| `dd if=/dev/nstX of=/dev/null`（读） | POST /tests/read | L2 | 6.1 |")
add("| `dd if=/dev/zero of=/dev/nstX`（写） | POST /tests/write | L3 | 6.2 |")
add("| 写+weof+读回+`cmp` 校验全流程 | POST /tests/write-verify | L3 | 6.4 |")
add("| `dmesg` / `journalctl -k` | GET /diagnostics/system | L1 | — |")
add("| sg_inq+vpd+tur+tapealert 综合 | GET /diagnostics/tape/{sg} | L1 | 5.6 |")
add("| 全链路只读测试 | POST /tests/full | L1 | — |")
add("| 审计溯源 | GET /commands/{id}、GET /audit/{request_id} | L1 | 7 |")
add("")
add("---")
add("")
add("# 三、基础与发现 API")
add("")
add("## 3.1 系统信息 `GET /api/v1/system/info`")
add("")
add(load(EV1, "02-system-info.json"))
add("")
add("## 3.2 内核驱动检查 `GET /api/v1/system/kernel`（CLI: lsmod）")
add("")
add(load(EV2, "40-system-kernel.json"))
add("")
add("## 3.3 IBM 检测 `GET /api/v1/system/ibm`（CLI: /dev/IBMtape*、ITDT）")
add("")
add(load(EV2, "41-system-ibm.json"))
add("")
add("## 3.4 依赖检查 `GET /api/v1/dependencies`")
add("")
add(load(EV1, "03-dependencies.json", 2000))
add("")
add("## 3.5 SCSI 发现 `GET /api/v1/discovery`（lsscsi -g）")
add("")
add(load(EV1, "04-discovery.json"))
add("")
add("## 3.6 扫描明细 `GET /api/v1/discovery/detail`（sg_scan + sg_map -i）")
add("")
add(load(EV2, "42-discovery-detail.json", 2400))
add("")
add("## 3.7 设备 Inquiry `GET /api/v1/devices/sg2/inquiry` 与 VPD/TUR")
add("")
add(load(EV2, "49-dev-inquiry.json"))
add("")
add("VPD 0x83：")
add("")
add(load(EV2, "50-dev-vpd.json", 1600))
add("")
add("TUR：")
add("")
add(load(EV2, "51-dev-tur.json"))
add("")
add("## 3.8 模式页 `GET /api/v1/devices/sg2/modes`（sg_modes -a）")
add("")
add(load(EV2, "44-modes.json", 2200))
add("")
add("## 3.9 日志页 `GET /api/v1/devices/sg2/logs` 与 `?page=0x11`（sg_logs）")
add("")
add("全页（sg_logs -a）：")
add("")
add(load(EV2, "52-dev-logs.json", 2400))
add("")
add("指定卷统计页 0x11：")
add("")
add(load(EV2, "43-logs-page11.json"))
add("")
add("---")
add("")
add("# 四、带库操作测试")
add("")
add("## 4.1 带库列表与 Inquiry")
add("")
add(load(EV1, "10-libraries.json"))
add("")
add(load(EV1, "11-lib-inquiry.json"))
add("")
add("## 4.2 带库状态 `GET /api/v1/libraries/sg1/status`（mtx status）")
add("")
add(load(EV1, "12-lib-status.json", 1800))
add("")
add("## 4.3 结构化 Inventory `GET /api/v1/libraries/sg1/inventory`")
add("")
add(load(EV1, "13-lib-inventory.json", 2200))
add("")
add("## 4.4 装载磁带 `POST /api/v1/libraries/sg1/load`（LEVEL 2）")
add("")
add(load(EV1, "14-lib-load.json"))
add("")
add("装载后状态（DTE 0 = Full, IBM015LA）：")
add("")
add(load(EV1, "15-lib-status-loaded.json", 1600))
add("")
add("## 4.5 卸载归位 `POST /api/v1/libraries/sg1/unload`")
add("")
add(load(EV1, "16-lib-unload.json"))
add("")
add("## 4.6 错误用例：非法槽位（INVALID_SLOT）")
add("")
add(load(EV1, "17-lib-load-err.json"))
add("")
add("## 4.7 错误用例：不存在的带库（sg9）")
add("")
add(load(EV1, "18-lib-load-busy.json"))
add("")
add("---")
add("")
add("# 五、带机操作测试")
add("")
add("先装载测试带：")
add("")
add(load(EV1, "19-lib-load2.json"))
add("")
add("## 5.1 带机状态 `GET /api/v1/drives/nst1/status`（mt status）")
add("")
add(load(EV1, "20-drive-status.json"))
add("")
add("## 5.2 TapeAlert `GET /api/v1/drives/sg2/tapealert`（sg_logs -p 0x2e）")
add("")
add(load(EV1, "21-drive-tapealert.json", 2000))
add("")
add("## 5.3 磁带回绕 `POST /api/v1/drives/nst1/position {rewind}`")
add("")
add(load(EV1, "22-drive-position.json"))
add("")
add("## 5.4 磁带定位 fsf `POST /api/v1/drives/nst1/position {fsf 1}`")
add("")
add(load(EV1, "23-drive-fsf.json"))
add("")
add("## 5.5 压缩状态 `GET /api/v1/drives/nst1/compression`")
add("")
add(load(EV1, "24-drive-compression.json"))
add("")
add("## 5.6 错误用例：非法操作名（INVALID_OPERATION）")
add("")
add(load(EV1, "25-drive-err.json"))
add("")
add("## 5.7 综合诊断 `GET /api/v1/diagnostics/tape/sg2`")
add("")
add(load(EV1, "26-diag-tape.json", 2600))
add("")
add("---")
add("")
add("# 六、读写 IO 测试")
add("")
add("> 读写在 FULL 模式实例（端口 8002）执行；写类接口要求请求体 `allow_write:true` + `test_media` + `confirm:true`。")
add("")
add("## 6.1 读测试 `POST /api/v1/tests/read`（dd 读）")
add("")
add(load(EV1, "30-read.json"))
add("")
add("## 6.2 写测试 `POST /api/v1/tests/write`（dd 写 256MB，18.2s）")
add("")
add(load(EV1, "32-write.json"))
add("")
add("## 6.3 错误用例：未授权写文件标记（weof 被 FULL 门禁拦截）")
add("")
add(load(EV2, "47-weof-unauth.json"))
add("")
add("## 6.4 写后读回+内容校验 `POST /api/v1/tests/write-verify`（CLI: dd→weof→rewind→dd→cmp 全流程）")
add("")
add(load(EV2, "46-write-verify.json"))
add("")
add("返回结构说明：`steps` 数组完整记录 5 步链路（rewind → write 256MB/8.1s → weof → read_verify 0.4s → content_verify CONTENT_VERIFY_OK），每步含 command_id 可溯源。")
add("")
add("## 6.5 错误用例：未授权写测试（allow_write=false）")
add("")
add(load(EV1, "31-write-unauth.json"))
add("")
add("## 6.6 写后读回验证 `POST /api/v1/tests/read`")
add("")
add(load(EV1, "33-read-after-write.json"))
add("")
add("## 6.7 测试后卸载归位 `POST /api/v1/libraries/sg1/unload`")
add("")
add(load(EV1, "34-unload-final.json"))
add("")
add("---")
add("")
add("# 七、审计与溯源 API")
add("")
add("```")
add("GET /api/v1/commands/{command_id}   # 单条命令: command/stdout/stderr/exit_code/duration/result")
add("GET /api/v1/audit/{request_id}      # 请求→命令链: 一次 API 调用的全部底层命令")
add("```")
add("")
add("任何响应中的 `command_id` 均可在测试机 `audit/commands/CMD-*/` 找到原始 stdout.txt / stderr.txt / command.json。")
add("")
add("---")
add("")
add("# 八、测试结果汇总")
add("")
add("| 章节 | 用例 | 结果 |")
add("|---|---|---|")
add("| 基础与发现 | info / kernel / ibm / dependencies / discovery / detail / inquiry / modes / logs(全页+0x11) | 9/9 PASS |")
add("| 带库操作 | libraries / inquiry / status / inventory / load / unload | 6/6 PASS |")
add("| 带库错误用例 | INVALID_SLOT (slot=-1)、LIBRARY_NOT_FOUND (sg9) | 2/2 正确拦截 |")
add("| 带机操作 | status / tapealert / rewind / fsf / compression / 综合诊断 | 6/6 PASS |")
add("| 带机错误用例 | INVALID_OPERATION (format_c) | 1/1 正确拦截 |")
add("| 读写 IO | read / write 256MB / write-verify 全流程（含 weof+读回+cmp）/ 写后读回 / 卸载 | 5/5 PASS |")
add("| 读写错误用例 | WRITE_OPERATION_NOT_AUTHORIZED（weof 与 write 两处） | 2/2 正确拦截 |")
add("")
add("**结论：31 个真实硬件用例全部符合预期（含 5 个安全拦截用例）；Mock 单元/API/安全测试 52/52 通过；所有响应可经 request_id → command_id 溯源至原始命令输出。**")
add("")
add("# 九、服务启动与配置")
add("")
add("```bash")
add("# SAFE 模式（默认，只读）")
add("uvicorn app.main:app --host 0.0.0.0 --port 8000")
add("")
add("# DIAGNOSTIC 模式（允许 LEVEL 2 设备操作）")
add("TAPE_API_MODE=DIAGNOSTIC ALLOW_DEVICE_OPERATION=true uvicorn app.main:app --port 8001")
add("")
add("# FULL 模式（允许 LEVEL 3 写测试，需请求体双重授权）")
add("TAPE_API_MODE=FULL ALLOW_DEVICE_OPERATION=true ALLOW_WRITE=true TEST_MEDIA=IBM015LA \\")
add("  uvicorn app.main:app --port 8002")
add("```")
add("")
add("环境变量完整清单见 `.env.example`；错误码表与安全说明见 `docs/API.md`。")
add("")

out = os.path.join(ROOT, "docs", "API-usage-manual.md")
open(out, "w").write("\n".join(L) + "\n")
print("written", out, os.path.getsize(out), "bytes,", len(L), "lines")
