server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://tape-api:8001/api/;
        proxy_read_timeout 7200s;
        proxy_send_timeout 7200s;
    }
}
