// CLI Playground 命令目录：手工维护，与后端 commands/adapters.py 白名单 1:1
// 每条 = Linux CLI 命令 ↔ HTTP 端点映射（实测 186 v1.2.2 后端；缺省参数与后端默认一致）
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type AnyObj = Record<string, any>;

export type CliTool = 'mt' | 'mtx' | 'sg' | 'lsscsi' | 'sys' | 'dd';
export type Level = 'L1' | 'L2' | 'L3';

export interface CliParam {
  name: string;
  in: 'path' | 'query';
  default?: string;
  options?: string[]; // 常用取值（下拉可改可输）
}

export interface CliCommand {
  id: string;
  group: string; // CLI_GROUPS key
  tool: CliTool;
  name: string; // 短名，如 "mt status"
  cli: string; // 完整 CLI 等价命令（展示/复制）
  method: 'GET' | 'POST';
  path: string; // /api/v1 下的相对路径
  level: Level;
  summary: string;
  params: CliParam[];
  hasBody?: boolean;
  bodyDefault?: string;
  isJob?: boolean; // 默认 202 异步（dd 测试类），前端轮询 /jobs/{id}
}

export const CLI_GROUPS: { key: string; label: string }[] = [
  { key: 'sg', label: 'sg3_utils SCSI' },
  { key: 'mtx', label: 'mtx 带库' },
  { key: 'mt-read', label: 'mt 只读' },
  { key: 'mt-pos', label: 'mt 定位 L2' },
  { key: 'mt-write', label: 'mt 写/破坏 L3' },
  { key: 'mt-set', label: 'mt 参数设置' },
  { key: 'sys', label: '系统探测' },
  { key: 'dd', label: 'dd 读写测试' },
];

const SG = 'sg2'; // 带机 sg 节点（实测 inquiry PDT=1 tape）
const CH = 'sg1'; // 带库 changer
const NST = 'nst1'; // 带机磁带设备
const MEDIA = 'IBM015LA';

export const CLI_CATALOG: CliCommand[] = [
  // ---------- sg3_utils / lsscsi ----------
  { id: 'lsscsi', group: 'sg', tool: 'lsscsi', name: 'lsscsi -g', cli: 'lsscsi -g',
    method: 'GET', path: '/discovery', level: 'L1',
    summary: '列出全部 SCSI 设备（含 /dev/sgN 对应关系）', params: [] },
  { id: 'sg-scan', group: 'sg', tool: 'sg', name: 'sg_scan + sg_map', cli: 'sg_scan && sg_map -i',
    method: 'GET', path: '/discovery/detail', level: 'L1',
    summary: 'SCSI 扫描 + sg/nst/厂商型号映射表', params: [] },
  { id: 'sg-inq', group: 'sg', tool: 'sg', name: 'sg_inq', cli: `sg_inq /dev/${SG}`,
    method: 'GET', path: '/devices/{sg_device}/inquiry', level: 'L1',
    summary: '标准 INQUIRY：厂商/型号/序列号',
    params: [{ name: 'sg_device', in: 'path', default: SG }] },
  { id: 'sg-vpd', group: 'sg', tool: 'sg', name: 'sg_vpd', cli: `sg_vpd -p 0x80 /dev/${SG}`,
    method: 'GET', path: '/devices/{sg_device}/vpd', level: 'L1',
    summary: '关键产品数据 VPD（0x80 序列号 / 0x83 标识）',
    params: [{ name: 'sg_device', in: 'path', default: SG },
      { name: 'page', in: 'query', default: '0x80', options: ['0x80', '0x83'] }] },
  { id: 'sg-turs', group: 'sg', tool: 'sg', name: 'sg_turs', cli: `sg_turs /dev/${SG}`,
    method: 'GET', path: '/devices/{sg_device}/tur', level: 'L1',
    summary: 'TEST UNIT READY：设备就绪检查',
    params: [{ name: 'sg_device', in: 'path', default: SG }] },
  { id: 'sg-modes', group: 'sg', tool: 'sg', name: 'sg_modes', cli: `sg_modes -a /dev/${SG}`,
    method: 'GET', path: '/devices/{sg_device}/modes', level: 'L1',
    summary: '全部 MODE SENSE 模式页',
    params: [{ name: 'sg_device', in: 'path', default: SG }] },
  { id: 'sg-logs', group: 'sg', tool: 'sg', name: 'sg_logs', cli: `sg_logs -a /dev/${SG}`,
    method: 'GET', path: '/devices/{sg_device}/logs', level: 'L1',
    summary: 'LOG SENSE 日志页（0x11 卷统计 / 0x2e TapeAlert / 空=全部）',
    params: [{ name: 'sg_device', in: 'path', default: SG },
      { name: 'page', in: 'query', default: '', options: ['', '0x11', '0x17', '0x2e'] }] },
  { id: 'sg-tapealert', group: 'sg', tool: 'sg', name: 'TapeAlert', cli: `sg_logs -p 0x2e /dev/${SG}`,
    method: 'GET', path: '/drives/{sg_device}/tapealert', level: 'L1',
    summary: 'TapeAlert 0x2e 页：磁带/带机告警标志',
    params: [{ name: 'sg_device', in: 'path', default: SG }] },
  { id: 'sg-persist', group: 'sg', tool: 'sg', name: 'sg_persist', cli: `sg_persist /dev/${SG}`,
    method: 'GET', path: '/scsi/{device}/persist', level: 'L1',
    summary: 'PERSISTENT RESERVE IN：持久预留状态',
    params: [{ name: 'device', in: 'path', default: SG }] },
  { id: 'sg-reset', group: 'sg', tool: 'sg', name: 'sg_reset -d', cli: `sg_reset -d /dev/${SG}`,
    method: 'POST', path: '/scsi/{device}/reset', level: 'L2',
    summary: 'SCSI 设备复位（需 confirm）',
    params: [{ name: 'device', in: 'path', default: SG }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },

  // ---------- mtx 带库 ----------
  { id: 'mtx-inquiry', group: 'mtx', tool: 'mtx', name: 'mtx inquiry', cli: `mtx -f /dev/${CH} inquiry`,
    method: 'GET', path: '/libraries/{changer}/inquiry', level: 'L1',
    summary: '带库 INQUIRY：厂商/型号/固件',
    params: [{ name: 'changer', in: 'path', default: CH }] },
  { id: 'mtx-status', group: 'mtx', tool: 'mtx', name: 'mtx status', cli: `mtx -f /dev/${CH} status`,
    method: 'GET', path: '/libraries/{changer}/status', level: 'L1',
    summary: '全部槽位/驱动器状态与条码',
    params: [{ name: 'changer', in: 'path', default: CH }] },
  { id: 'mtx-inventory', group: 'mtx', tool: 'mtx', name: 'mtx inventory', cli: `mtx -f /dev/${CH} inventory`,
    method: 'POST', path: '/libraries/{changer}/inventory', level: 'L2',
    summary: '发起带库盘点（条码重扫）',
    params: [{ name: 'changer', in: 'path', default: CH }] },
  { id: 'mtx-load', group: 'mtx', tool: 'mtx', name: 'mtx load', cli: `mtx -f /dev/${CH} load 1 0`,
    method: 'POST', path: '/libraries/{changer}/load', level: 'L2',
    summary: '装带（v1.2）：barcode 磁带条码 + drive_sn 带机序列号，动作前双状态检查',
    params: [{ name: 'changer', in: 'path', default: CH }],
    hasBody: true, bodyDefault: `{\n  "barcode": "IBM006LA",\n  "drive_sn": "607B811E03",\n  "confirm": true\n}` },
  { id: 'mtx-unload', group: 'mtx', tool: 'mtx', name: 'mtx unload', cli: `mtx -f /dev/${CH} unload 6 0`,
    method: 'POST', path: '/libraries/{changer}/unload', level: 'L2',
    summary: '卸带（v1.2）：barcode + slot 目标槽（检查存在且空；缺省自动回原槽）',
    params: [{ name: 'changer', in: 'path', default: CH }],
    hasBody: true, bodyDefault: `{\n  "barcode": "IBM015LA",\n  "slot": 7,\n  "confirm": true\n}` },
  { id: 'mtx-transfer', group: 'mtx', tool: 'mtx', name: 'mtx transfer', cli: `mtx -f /dev/${CH} transfer 1 2`,
    method: 'POST', path: '/libraries/{changer}/transfer', level: 'L2',
    summary: '槽间搬移磁带 1 → 2',
    params: [{ name: 'changer', in: 'path', default: CH }],
    hasBody: true, bodyDefault: `{\n  "source": 1,\n  "destination": 2,\n  "confirm": true\n}` },
  { id: 'mtx-position', group: 'mtx', tool: 'mtx', name: 'mtx position', cli: `mtx -f /dev/${CH} position 1`,
    method: 'POST', path: '/libraries/{changer}/robot/position', level: 'L2',
    summary: '机械手移动到指定元件位置',
    params: [{ name: 'changer', in: 'path', default: CH }],
    hasBody: true, bodyDefault: `{\n  "element": 1,\n  "confirm": true\n}` },
  { id: 'mtx-exchange', group: 'mtx', tool: 'mtx', name: 'mtx exchange', cli: `mtx -f /dev/${CH} exchange 1 2`,
    method: 'POST', path: '/libraries/{changer}/exchange', level: 'L2',
    summary: '交换两个槽位的磁带',
    params: [{ name: 'changer', in: 'path', default: CH }],
    hasBody: true, bodyDefault: `{\n  "source": 1,\n  "destination": 2,\n  "confirm": true\n}` },
  { id: 'mtx-first', group: 'mtx', tool: 'mtx', name: 'mtx first', cli: `mtx -f /dev/${CH} first`,
    method: 'POST', path: '/libraries/{changer}/robot/first', level: 'L2',
    summary: '机械手回到第一个槽位',
    params: [{ name: 'changer', in: 'path', default: CH }] },
  { id: 'mtx-next', group: 'mtx', tool: 'mtx', name: 'mtx next', cli: `mtx -f /dev/${CH} next`,
    method: 'POST', path: '/libraries/{changer}/robot/next', level: 'L2',
    summary: '机械手移动到下一槽位',
    params: [{ name: 'changer', in: 'path', default: CH }] },
  { id: 'mtx-last', group: 'mtx', tool: 'mtx', name: 'mtx last', cli: `mtx -f /dev/${CH} last`,
    method: 'POST', path: '/libraries/{changer}/robot/last', level: 'L2',
    summary: '机械手移动到最后槽位',
    params: [{ name: 'changer', in: 'path', default: CH }] },

  // ---------- mt 只读 ----------
  { id: 'mt-status', group: 'mt-read', tool: 'mt', name: 'mt status', cli: `mt -f /dev/${NST} status`,
    method: 'GET', path: '/drives/{drive}/status', level: 'L1',
    summary: '磁带当前位置/块大小/密度/状态位',
    params: [{ name: 'drive', in: 'path', default: NST }] },
  { id: 'mt-tell', group: 'mt-read', tool: 'mt', name: 'mt tell', cli: `mt -f /dev/${NST} tell`,
    method: 'GET', path: '/drives/{drive}/tell', level: 'L1',
    summary: '当前块位置（块设备）',
    params: [{ name: 'drive', in: 'path', default: NST }] },
  { id: 'mt-densities', group: 'mt-read', tool: 'mt', name: 'mt densities', cli: `mt -f /dev/${NST} densities`,
    method: 'GET', path: '/drives/{drive}/densities', level: 'L1',
    summary: '支持的密度码列表',
    params: [{ name: 'drive', in: 'path', default: NST }] },
  { id: 'mt-options', group: 'mt-read', tool: 'mt', name: 'stshowoptions', cli: `mt -f /dev/${NST} stshowoptions`,
    method: 'GET', path: '/drives/{drive}/options', level: 'L1',
    summary: 'st 驱动当前选项',
    params: [{ name: 'drive', in: 'path', default: NST }] },
  { id: 'mt-comp-get', group: 'mt-read', tool: 'mt', name: 'mt compression', cli: `mt -f /dev/${NST} compression`,
    method: 'GET', path: '/drives/{nst_device}/compression', level: 'L1',
    summary: '查询压缩开关状态（旧只读端点）',
    params: [{ name: 'nst_device', in: 'path', default: NST }] },

  // ---------- mt 定位（L2 物理移动） ----------
  { id: 'mt-rewind', group: 'mt-pos', tool: 'mt', name: 'mt rewind', cli: `mt -f /dev/${NST} rewind`,
    method: 'POST', path: '/drives/{drive}/rewind', level: 'L2',
    summary: '倒带至 BOT',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-offline', group: 'mt-pos', tool: 'mt', name: 'mt offline', cli: `mt -f /dev/${NST} offline`,
    method: 'POST', path: '/drives/{drive}/offline', level: 'L2',
    summary: '倒带并卸载（回槽）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-rewoffl', group: 'mt-pos', tool: 'mt', name: 'mt rewoffl', cli: `mt -f /dev/${NST} rewoffl`,
    method: 'POST', path: '/drives/{drive}/rewoffl', level: 'L2',
    summary: '倒带离线（rewind offline）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-eject', group: 'mt-pos', tool: 'mt', name: 'mt eject', cli: `mt -f /dev/${NST} eject`,
    method: 'POST', path: '/drives/{drive}/eject', level: 'L2',
    summary: '弹出磁带',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-retension', group: 'mt-pos', tool: 'mt', name: 'mt retension', cli: `mt -f /dev/${NST} retension`,
    method: 'POST', path: '/drives/{drive}/retension', level: 'L2',
    summary: '磁带重新张紧（全程走带）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-eod', group: 'mt-pos', tool: 'mt', name: 'mt eod', cli: `mt -f /dev/${NST} eod`,
    method: 'POST', path: '/drives/{drive}/eod', level: 'L2',
    summary: '定位到数据末尾 EOD（追加写入前用）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-load', group: 'mt-pos', tool: 'mt', name: 'mt load', cli: `mt -f /dev/${NST} load`,
    method: 'POST', path: '/drives/{drive}/load', level: 'L2',
    summary: '加载已装入的磁带',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-lock', group: 'mt-pos', tool: 'mt', name: 'mt lock', cli: `mt -f /dev/${NST} lock`,
    method: 'POST', path: '/drives/{drive}/lock', level: 'L2',
    summary: '锁定带机仓门（带库场景）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  { id: 'mt-unlock', group: 'mt-pos', tool: 'mt', name: 'mt unlock', cli: `mt -f /dev/${NST} unlock`,
    method: 'POST', path: '/drives/{drive}/unlock', level: 'L2',
    summary: '解锁带机仓门',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "confirm": true\n}' },
  ...(['fsf', 'bsf', 'fsr', 'bsr', 'fsfm', 'bsfm', 'fss', 'bss', 'asf'] as const).map((op) => ({
    id: `mt-${op}`, group: 'mt-pos', tool: 'mt' as CliTool, name: `mt ${op}`,
    cli: `mt -f /dev/${NST} ${op} 1`,
    method: 'POST' as const, path: '/drives/{drive}/position', level: 'L2' as Level,
    summary: {
      fsf: '前进 1 个文件标记', bsf: '后退 1 个文件标记', fsr: '前进 1 个块', bsr: '后退 1 个块',
      fsfm: '前进到下一文件标记前', bsfm: '后退到上一文件标记后', fss: '前进 1 个 setmark',
      bss: '后退 1 个 setmark', asf: '定位到第 N 个文件开头（count=文件号）',
    }[op],
    params: [{ name: 'drive', in: 'path' as const, default: NST }],
    hasBody: true,
    bodyDefault: `{\n  "operation": "${op}",\n  "count": 1,\n  "confirm": true\n}`,
  })),
  { id: 'mt-seek', group: 'mt-pos', tool: 'mt', name: 'mt seek', cli: `mt -f /dev/${NST} seek 0`,
    method: 'POST', path: '/drives/{drive}/seek', level: 'L2',
    summary: 'seek 到指定块号（变量块模式）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 0,\n  "confirm": true\n}' },
  { id: 'mt-partseek', group: 'mt-pos', tool: 'mt', name: 'mt partseek', cli: `mt -f /dev/${NST} partseek 0,0`,
    method: 'POST', path: '/drives/{drive}/partition/seek', level: 'L2',
    summary: '分区寻址：partition,block',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "partition": 0,\n  "block": 0,\n  "confirm": true\n}' },
  { id: 'mt-setpartition', group: 'mt-set', tool: 'mt', name: 'mt setpartition', cli: `mt -f /dev/${NST} setpartition 0`,
    method: 'POST', path: '/drives/{drive}/partition', level: 'L2',
    summary: '切换当前分区（partition 字段）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "partition": 0,\n  "confirm": true\n}' },
  { id: 'mt-compression', group: 'mt-set', tool: 'mt', name: 'mt compression 1', cli: `mt -f /dev/${NST} compression 1`,
    method: 'POST', path: '/drives/{drive}/compression', level: 'L2',
    summary: '设置压缩开关（enable）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "enable": true,\n  "confirm": true\n}' },
  { id: 'mt-setblk', group: 'mt-set', tool: 'mt', name: 'mt setblk', cli: `mt -f /dev/${NST} setblk 0`,
    method: 'POST', path: '/drives/{drive}/block-size', level: 'L2',
    summary: '块大小：0=变量块模式，>0=固定块',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "block_size": 0,\n  "confirm": true\n}' },
  { id: 'mt-setdensity', group: 'mt-set', tool: 'mt', name: 'mt setdensity', cli: `mt -f /dev/${NST} setdensity 0`,
    method: 'POST', path: '/drives/{drive}/density', level: 'L2',
    summary: '设置密度码（0=驱动器默认）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "density": 0,\n  "confirm": true\n}' },

  // ---------- mt 写操作（L3 破坏性） ----------
  { id: 'mt-weof', group: 'mt-write', tool: 'mt', name: 'mt weof', cli: `mt -f /dev/${NST} weof 1`,
    method: 'POST', path: '/drives/{drive}/weof', level: 'L3',
    summary: '写 N 个文件标记（结束当前文件）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 1,\n  "confirm": true\n}' },
  { id: 'mt-wset', group: 'mt-write', tool: 'mt', name: 'mt wset', cli: `mt -f /dev/${NST} wset 1`,
    method: 'POST', path: '/drives/{drive}/wset', level: 'L3',
    summary: '写 N 个 setmark',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 1,\n  "confirm": true\n}' },
  { id: 'mt-eof', group: 'mt-write', tool: 'mt', name: 'mt eof', cli: `mt -f /dev/${NST} eof 1`,
    method: 'POST', path: '/drives/{drive}/eof', level: 'L3',
    summary: 'mt eof = mt weof 别名',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 1,\n  "confirm": true\n}' },
  { id: 'mt-erase', group: 'mt-write', tool: 'mt', name: 'mt erase', cli: `mt -f /dev/${NST} erase`,
    method: 'POST', path: '/drives/{drive}/erase', level: 'L3',
    summary: '擦除（短擦 count=0；长擦传 count=1）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 0,\n  "confirm": true\n}' },
  { id: 'mt-mkpartition', group: 'mt-write', tool: 'mt', name: 'mt mkpartition', cli: `mt -f /dev/${NST} mkpartition 1`,
    method: 'POST', path: '/drives/{drive}/partition', level: 'L3',
    summary: '重新划分分区（破坏数据！只传 count）',
    params: [{ name: 'drive', in: 'path', default: NST }],
    hasBody: true, bodyDefault: '{\n  "count": 1,\n  "confirm": true\n}' },

  // ---------- 系统探测 ----------
  { id: 'sys-os', group: 'sys', tool: 'sys', name: 'cat os-release', cli: 'cat /etc/os-release',
    method: 'GET', path: '/system/os-release', level: 'L1',
    summary: '操作系统发行版信息', params: [] },
  { id: 'sys-uname', group: 'sys', tool: 'sys', name: 'uname -a', cli: 'uname -a',
    method: 'GET', path: '/system/uname', level: 'L1',
    summary: '内核全称', params: [] },
  { id: 'sys-hostname', group: 'sys', tool: 'sys', name: 'hostname', cli: 'hostname',
    method: 'GET', path: '/system/hostname', level: 'L1',
    summary: '主机名', params: [] },
  { id: 'sys-arch', group: 'sys', tool: 'sys', name: 'uname -m', cli: 'uname -m',
    method: 'GET', path: '/system/arch', level: 'L1',
    summary: 'CPU 架构', params: [] },
  { id: 'sys-user', group: 'sys', tool: 'sys', name: 'id', cli: 'id',
    method: 'GET', path: '/system/user', level: 'L1',
    summary: '当前运行用户/组', params: [] },
  { id: 'sys-kernel', group: 'sys', tool: 'sys', name: 'lsmod 内核模块', cli: "lsmod | grep -E 'st|sg|ch|lin_tape'",
    method: 'GET', path: '/system/kernel', level: 'L1',
    summary: 'st/sg/ch/lin_tape 模块加载状态', params: [] },
  { id: 'sys-ibm', group: 'sys', tool: 'sys', name: 'IBM 探测', cli: 'ls /dev/IBMtape*; command -v itdt',
    method: 'GET', path: '/system/ibm', level: 'L1',
    summary: 'IBMtape 驱动节点 + ITDT 安装检测', params: [] },
  { id: 'sys-info', group: 'sys', tool: 'sys', name: '系统信息汇总', cli: '(os-release + uname + hostname + arch + id)',
    method: 'GET', path: '/system/info', level: 'L1',
    summary: '一次取全：OS/内核/主机/架构/用户', params: [] },
  { id: 'sys-dmesg', group: 'sys', tool: 'sys', name: 'dmesg 过滤', cli: "dmesg | grep -Ei 'tape|scsi|st|sg' | tail -100",
    method: 'GET', path: '/diagnostics/dmesg', level: 'L1',
    summary: '内核日志过滤（tail 控制行数）',
    params: [{ name: 'tail', in: 'query', default: '100' }] },
  { id: 'sys-journal', group: 'sys', tool: 'sys', name: 'journalctl -k', cli: 'journalctl -k --no-pager | tail -100',
    method: 'GET', path: '/diagnostics/journalctl', level: 'L1',
    summary: '本次启动内核日志尾部',
    params: [{ name: 'tail', in: 'query', default: '100' }] },
  { id: 'sys-diag', group: 'sys', tool: 'sys', name: 'tape 诊断汇总', cli: 'mt status + sg_inq + TapeAlert',
    method: 'GET', path: '/diagnostics/tape/{sg_device}', level: 'L1',
    summary: '指定带机综合诊断',
    params: [{ name: 'sg_device', in: 'path', default: SG }] },

  // ---------- dd 读写测试 ----------
  { id: 'dd-write', group: 'dd', tool: 'dd', name: 'dd 写入', cli: `dd if=/dev/zero of=/dev/${NST} bs=1M count=${256}M`,
    method: 'POST', path: '/write', level: 'L3', isJob: true,
    summary: `写 ${MEDIA} 指定 MiB 数据（size_mb）`,
    params: [],
    hasBody: true,
    bodyDefault: `{\n  "drive": "${NST}",\n  "media": "${MEDIA}",\n  "size_mb": 256,\n  "allow_write": true,\n  "confirm": true\n}` },
  { id: 'dd-read', group: 'dd', tool: 'dd', name: 'dd 读回', cli: `dd if=/dev/${NST} of=/dev/null bs=1M`,
    method: 'POST', path: '/read', level: 'L2', isJob: true,
    summary: '从磁带读回数据（block_size）',
    params: [],
    hasBody: true,
    bodyDefault: `{\n  "drive": "${NST}",\n  "block_size": "1M",\n  "confirm": true\n}` },
  { id: 'dd-write-verify', group: 'dd', tool: 'dd', name: '写+读回校验', cli: 'dd 写 → dd 读回 → cmp 逐字节比对',
    method: 'POST', path: '/tests/write-verify', level: 'L3', isJob: true,
    summary: '写入并读回校验（最完整的功能测试）',
    params: [],
    hasBody: true,
    bodyDefault: `{\n  "drive": "${NST}",\n  "test_media": "${MEDIA}",\n  "size_mb": 256,\n  "allow_write": true,\n  "confirm": true\n}` },
  { id: 'dd-erase', group: 'dd', tool: 'dd', name: 'mt erase 擦除', cli: `mt -f /dev/${NST} erase`,
    method: 'POST', path: '/tests/erase', level: 'L3', isJob: true,
    summary: '测试介质擦除',
    params: [],
    hasBody: true,
    bodyDefault: `{\n  "drive": "${NST}",\n  "allow_write": true,\n  "confirm": true\n}` },
];

export const TOOL_COLORS: Record<CliTool, string> = {
  mt: 'geekblue', mtx: 'purple', sg: 'cyan', lsscsi: 'blue', sys: 'green', dd: 'volcano',
};

export const LEVEL_COLORS: Record<Level, string> = { L1: 'green', L2: 'orange', L3: 'red' };
